package Luokat.test;
// Generated by ComTest BEGIN
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import Luokat.Reissu;
import Luokat.Reissut;
import Luokat.Tulkki;
import Luokat.Saaliit;
import static org.junit.Assert.*;
import org.junit.*;
import static Luokat.Reissut.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.31 16:23:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReissutTest {



  // Generated by ComTest BEGIN
  /** testMain131 */
  @Test
  public void testMain131() {    // Reissut: 131
    Saaliit saaliita = new Saaliit(8); 
    Reissut test = new Reissut(saaliita); 
    test.getReissut().clear(); 
    Reissu t0 = new Reissu(Reissu.sToDate("1.12.2323"), "ka", "pilvi", new ArrayList<>(), false); 
    Reissu t1 = new Reissu(Reissu.sToDate("12.12.2023"), "jk", "sade", new ArrayList<>(), false); 
    Reissu t2 = new Reissu(Reissu.sToDate("12.12.1223"), "sk", "aurinko", new ArrayList<>(), false); 
    Reissu t3 = new Reissu(Reissu.sToDate("15.11.2024"), "ka", "pilvi", new ArrayList<>(), false); 
    test.lisaaListaan(t1); 
    test.lisaaListaan(t2); 
    test.lisaaListaan(t3); 
    test.lisaaListaan(t0); 
    assertEquals("From: Reissut line: 157", 4, test.getReissut().size()); 
    t1.poistetaan(); 
    test.removeReissu(); 
    assertEquals("From: Reissut line: 161", 3, test.getReissut().size()); 
    List<Reissu> a = new ArrayList<>(); 
    a = etsi("*,*,1223", test); 
    assertEquals("From: Reissut line: 165", 1, a.size()); 
  } // Generated by ComTest END
}